version: '3.7'

services:
  onlyoffice-documentserver:
    build:
      context: .
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PASSWORD}
      - AMQP_URI=${AMQP_URI}
      # Uncomment lines below to enable JSON Web Token validation
      - JWT_ENABLED=${JWT_ENABLED}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_HEADER=${JWT_HEADER}
      - JWT_IN_BODY=${JWT_IN_BODY}
    ports:
      - '${ONLYOFFICE_HTTP_PORT}:80'
      - '${ONLYOFFICE_HTTPS_PORT}:443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
      - /var/www/onlyoffice/Data
      - /var/log/onlyoffice
      - /var/lib/onlyoffice/documentserver/App_Data/cache/files
      - /var/www/onlyoffice/documentserver-example/public/files
      - /usr/share/fonts

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'
